FROM node:18-alpine AS development
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN yarn install
COPY ./.eslintrc.js ./.eslintrc.js
COPY ./.prettierrc ./.prettierrc
COPY ./tsconfig.build.json ./tsconfig.build.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./nest-cli.json ./nest-cli.json
COPY ./libs ./libs
COPY ./apps/als-vendor ./apps/als-vendor

EXPOSE 3003
CMD ["yarn","run","start:dev","als-vendor"]

