export const userInstallerData = [
  {
    username: 'Muhammad_Ahmad',
    email: 'm.ahmad@techverx.com',
    password: '12345678',
    phone_number: '123-654-5304',
    role: 'admin',
    first_name: 'Muhammad',
    last_name: 'Ahmad',
  },
  {
    username: 'Muhammad_Anees',
    email: 'anees.ahmed@techverx.com',
    password: '12345678',
    phone_number: '518-817-9485',
    role: 'admin',
    first_name: 'Muhammad',
    last_name: 'Anees',
  },
  {
    username: 'Abdul_Rafay',
    email: 'abdul.rafay@techverx.com',
    password: '12345678',
    phone_number: '917-565-4151',
    role: 'admin',
    first_name: 'Abdul',
    last_name: 'Rafay',
  },
  {
    username: 'Malik_Idrees',
    email: 'malik.idrees@techverx.com',
    password: '12345678',
    phone_number: '341-623-9014',
    role: 'admin',
    first_name: 'Malik',
    last_name: 'Idrees',
  },
  {
    username: 'Muhammad_Ahmed',
    email: 'ahmed.kiani@techverx.com',
    password: '12345678',
    phone_number: '673-962-1181',
    role: 'admin',
    first_name: 'Muhammad',
    last_name: 'Ahmed',
  },
  {
    username: 'Sheikh_Danyyal',
    email: 'danyyal.ali@techverx.com',
    password: '12345678',
    phone_number: '670-224-7306',
    role: 'admin',
    first_name: 'Sheikh',
    last_name: 'Danyyal',
  },
  {
    username: 'Zain_Asim',
    email: 'zain.asim@techverx.com',
    password: '12345678',
    phone_number: '955-805-0873',
    role: 'admin',
    first_name: 'Zain',
    last_name: 'Asim',
  },
  {
    username: 'Ahmed_Raza',
    email: 'ahmad.raza@techverx.com',
    password: '12345678',
    phone_number: '205-795-8280',
    role: 'admin',
    first_name: 'Ahmed',
    last_name: 'Raza',
  },
  {
    username: 'Muhammad_Fahad',
    email: 'Muhammad.Fahad@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Muhammad',
    last_name: 'Fahad',
  },
  {
    username: 'Abdullah_Tariq',
    email: 'abdullah.tariq@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Abdullah',
    last_name: 'Tariq',
  },
  {
    username: 'Ali_Hassan_Kazmi',
    email: 'syedali.hassan@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Ali',
    last_name: 'Hassan',
  },
  {
    username: 'Hassan_Saleem',
    email: 'hassaan.saleem@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Hassan',
    last_name: 'Saleem',
  },
  {
    username: 'Mehran_Ayoub',
    email: 'mehran.ayoub@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Mehran',
    last_name: 'Ayoub',
  },
  {
    username: 'Sara_Akbar',
    email: 'sarah.akbar@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Sara',
    last_name: 'Akbar',
  },
  {
    username: 'Hassan_Afaq',
    email: 'hassan.afaq@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Hassan',
    last_name: 'Afaq',
  },
  {
    username: 'Khalid_Zafar',
    email: 'khalid.zafar@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Khalid',
    last_name: 'Zafar',
  },
  {
    username: 'Muhammad_Suleman',
    email: 'muhammad.suleman@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Muhammad',
    last_name: 'Suleman',
  },
  {
    username: 'Suleman_Bin_Kauser',
    email: 'imsalman@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Suleman',
    last_name: 'Bin Kauser',
  },
  {
    username: 'Jonathan_Edwards',
    email: 'jedwards@thealsgroup.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Jonathan',
    last_name: 'Edwards',
  },
  {
    username: 'Albert',
    email: 'asica@thealsgroup.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Albert',
    last_name: 'L. Sica',
  },
  {
    username: 'Courtney_Moy',
    email: 'cmoy@thealsgroup.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Courtney',
    last_name: 'Moy',
  },
  {
    username: 'Fahad_Shehzad',
    email: 'fahad+als@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Fahad',
    last_name: 'Shehzad',
  },
  {
    username: 'Fahad_Shehzad_Extra',
    email: 'fahad@techverx.com',
    password: '12345678',
    phone_number: '179-121-1928',
    role: 'admin',
    first_name: 'Fahad',
    last_name: 'Shehzad',
  },
];
